version: '3.8'

services:
        app:
                build: .
                container_name: fantumcr.azurecr.io/presave-microservice:v2
                ports:
                        - '8000:8000'
                depends_on:
                        - redis
                environment:
                        - REDIS_HOST=redis
                        - REDIS_PORT=6379
                networks:
                        - app-network

        redis:
                image: redis:alpine
                container_name: redis-server
                ports:
                        - '6379:6379'
                networks:
                        - app-network

networks:
        app-network:
                driver: bridge
